services:
  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordle_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./wordle_db.sql:/docker-entrypoint-initdb.d/wordle_db.sql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_interface
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:
